### ISSUE TITLE
New screenshot

### ISSUE THREAD

**Issue by urre** [basscss/showcase#1]
Hi, thanks for including Linknest on the showcase! I've rebuilt the startpage a bit. Would be great if you can update the screenshot!

https://linknest.cc/

Thanks

**Comment by jxnblk** [comment]
Hey, sorry for the delay. I'll try to get an updated screenshot up shortly.

**Comment by urre** [comment]
Cool! No worries. Thanks!

**Comment by jxnblk** [comment]
Updated the screenshot, but just as a heads up, your site is over 1MB and took over 12 seconds to load. You might want to look into that.

**Comment by urre** [comment]
@jxnblk Thanks. That transparent png got to big. Switched to a smaller jpg now. Actually shaved of 300 kb. Thanks a lot!
